sources:
  - { method: "<java.net.Authenticator: java.net.PasswordAuthentication getPasswordAuthentication()>", index: result, type: "java.net.PasswordAuthentication" }
  - { method: "<java.net.Authenticator: java.lang.String getRequestHost()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.Authenticator: int getRequestPort()>", index: result, type: "int" }
  - { method: "<java.net.Authenticator: java.lang.String getRequestingProtocol()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.Authenticator: java.lang.String getRequestingPrompt()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.Authenticator: java.net.InetAddress getRequestingSite()>", index: result, type: "java.net.InetAddress" }
  - { method: "<java.net.Authenticator: java.net.URL getRequestingURL()>", index: result, type: "java.net.URL" }
  - { method: "<java.net.Authenticator: java.lang.String getRequestingScheme()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.Authenticator: java.net.Authenticator.RequestorType getRequestorType()>", index: result, type: "java.net.Authenticator$RequestorType" }
  - { method: "<java.net.Authenticator: java.net.PasswordAuthentication requestPasswordAuthentication(java.net.InetAddress,int,java.lang.String,java.lang.String,java.lang.String)>", index: result, type: "java.net.PasswordAuthentication" }
  - { method: "<java.net.Authenticator: java.net.PasswordAuthentication requestPasswordAuthentication(java.lang.String,java.net.InetAddress,int,java.lang.String,java.lang.String,java.lang.String)>", index: result, type: "java.net.PasswordAuthentication" }
  - { method: "<java.net.Authenticator: java.net.PasswordAuthentication requestPasswordAuthentication(java.lang.String,java.net.InetAddress,int,java.lang.String,java.lang.String,java.lang.String,java.net.URL,java.net.Authenticator$RequestorType)>", index: result, type: "java.net.PasswordAuthentication" }

  - { method: "<java.net.ContentHandler: java.lang.Object getContent(java.net.URLConnection)>", index: result, type: "java.lang.Object" }
  - { method: "<java.net.ContentHandler: java.lang.Object getContent(java.net.URLConnection,java.lang.Class[])>", index: result, type: "java.lang.Object" }

  - { method: "<java.net.CookieHandler: java.util.Map get(java.net.URI,java.util.Map)>", index: result, type: "java.util.Map" }

  - { method: "<java.net.CookieManager: java.util.Map get(java.net.URI,java.util.Map)>", index: result, type: "java.util.Map" }

  - { method: "<java.net.DatagramPacket: java.net.InetAddress getAddress()>", index: result, type: "java.net.InetAddress" }
  - { method: "<java.net.DatagramPacket: byte[] getData()>", index: result, type: "byte[]" }
  - { method: "<java.net.DatagramPacket: java.net.SocketAddress getSocketAddress()>", index: result, type: "java.net.SocketAddress" }
  - { method: "<java.net.DatagramPacket: int getPort()>", index: result, type: "int" }

  - { method: "<java.net.DatagramSocket: java.net.InetAddress getLocalAddress()>", index: result, type: "java.net.InetAddress" }
  - { method: "<java.net.DatagramSocket: java.net.SocketAddress getLocalSocketAddress()>", index: result, type: "java.net.SocketAddress" }
  - { method: "<java.net.DatagramSocket: java.net.SocketAddress getRemoteSocketAddress()>", index: result, type: "java.net.SocketAddress" }
  - { method: "<java.net.DatagramSocket: java.net.DatagramChannel getChannel()>", index: result, type: "java.net.DatagramChannel" }
  - { method: "<java.net.DatagramSocket: java.net.InetAddress getInetAddress()>", index: result, type: "java.net.InetAddress" }
  - { method: "<java.net.DatagramSocket: int getPort()>", index: result, type: "int" }

  - { method: "<java.net.HttpCookie: java.lang.String getComment()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getCommentURL()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getDiscard()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getDomain()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getMaxAge()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getPath()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getPortlist()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getSecure()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getValue()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getVersion()>", index: result, type: "java.lang.String" }
  - { method: "<java.net.HttpCookie: java.lang.String getName()>", index: result, type: "java.lang.String" }

